import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  root: '.',
  base: process.env.GITHUB_ACTIONS ? '/Probability-education/' : './',
  resolve: {
    alias: {
      '@shared': resolve(__dirname, 'src/shared'),
      '@modules': resolve(__dirname, 'src/modules'),
    },
  },
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        convergenceModes: resolve(__dirname, 'src/modules/2.1-convergence-modes/index.html'),
        llnLab: resolve(__dirname, 'src/modules/2.3-lln-lab/index.html'),
        cltStudio: resolve(__dirname, 'src/modules/2.4-clt-studio/index.html'),
        martingaleExplorer: resolve(__dirname, 'src/modules/4.2-martingale-explorer/index.html'),
        donsker: resolve(__dirname, 'src/modules/5.1-donsker/index.html'),
        brownianProperties: resolve(__dirname, 'src/modules/5.2-brownian-properties/index.html'),
        markovDashboard: resolve(__dirname, 'src/modules/6.1-markov-dashboard/index.html'),
        spcControlChart: resolve(__dirname, 'src/modules/mq-1-spc-control-chart/index.html'),
        funnelPlot: resolve(__dirname, 'src/modules/mq-2-funnel-plot/index.html'),
        cusumChart: resolve(__dirname, 'src/modules/mq-3-cusum-chart/index.html'),
        paretoChart: resolve(__dirname, 'src/modules/mq-4-pareto-chart/index.html'),
        sigmaAlgebra: resolve(__dirname, 'src/modules/1.1-sigma-algebra/index.html'),
        measureRandomVars: resolve(__dirname, 'src/modules/1.2-measure-random-vars/index.html'),
        lebesgueRiemann: resolve(__dirname, 'src/modules/1.3-lebesgue-riemann/index.html'),
        cantorSet: resolve(__dirname, 'src/modules/1.4-cantor-set/index.html'),
        borelCantelli: resolve(__dirname, 'src/modules/2.2-borel-cantelli/index.html'),
        characteristicFunctions: resolve(__dirname, 'src/modules/3.1-characteristic-functions/index.html'),
        convolutionCFs: resolve(__dirname, 'src/modules/3.2-convolution-cfs/index.html'),
        conditionalExpectation: resolve(__dirname, 'src/modules/4.1-conditional-expectation/index.html'),
        ergodicMixing: resolve(__dirname, 'src/modules/6.2-ergodic-mixing/index.html'),
        diagnosticTesting: resolve(__dirname, 'src/modules/mq-5-diagnostic-testing/index.html'),
        metaAnalysis: resolve(__dirname, 'src/modules/mq-6-meta-analysis/index.html'),
        clinicalStatistics: resolve(__dirname, 'src/modules/mq-7-clinical-statistics/index.html'),
        itoIntegral: resolve(__dirname, 'src/modules/7.1-ito-integral/index.html'),
        sdeSolver: resolve(__dirname, 'src/modules/7.2-sde-solver/index.html'),
        priorPosterior: resolve(__dirname, 'src/modules/8.1-prior-posterior/index.html'),
        mcmcExplorer: resolve(__dirname, 'src/modules/8.2-mcmc-explorer/index.html'),
        entropyKl: resolve(__dirname, 'src/modules/9.1-entropy-kl/index.html'),
        mutualInformation: resolve(__dirname, 'src/modules/9.2-mutual-information/index.html'),
        ebmIntegration: resolve(__dirname, 'src/modules/mq-8-ebm-integration/index.html'),
        diseaseModeling: resolve(__dirname, 'src/modules/mq-8-disease-modeling/index.html'),
        vaccinePreventable: resolve(__dirname, 'src/modules/mq-9-vaccine-preventable/index.html'),
        introProbStats: resolve(__dirname, 'src/modules/intro-prob-stats/index.html'),
        stochasticFinance: resolve(__dirname, 'src/modules/fm-1-stochastic-finance/index.html'),
        agentSimulation: resolve(__dirname, 'src/modules/abm-1-agent-simulation/index.html'),
        predatorPreyD3: resolve(__dirname, 'src/modules/abm-2-predator-prey-d3/index.html'),
        predatorPreyWasm: resolve(__dirname, 'src/modules/abm-3-predator-prey-wasm/index.html'),
        vaccineImpact: resolve(__dirname, 'src/modules/mq-10-vaccine-impact/index.html'),
        rhPatientFlow: resolve(__dirname, 'src/modules/rh-7-patient-flow/index.html'),
        rhCatchmentArea: resolve(__dirname, 'src/modules/rh-1-catchment-accessibility/index.html'),
        rhOccupancyCalc: resolve(__dirname, 'src/modules/rh-5-occupancy-calculator/index.html'),
        rhMigration: resolve(__dirname, 'src/modules/rh-3-migration-modeling/index.html'),
        rhDisease: resolve(__dirname, 'src/modules/rh-4-disease-burden/index.html'),
        rhWorkforce: resolve(__dirname, 'src/modules/rh-8-workforce-optimization/index.html'),
        rhLogistics: resolve(__dirname, 'src/modules/rh-9-supply-chain/index.html'),
        rhFinance: resolve(__dirname, 'src/modules/rh-10-financial-risk/index.html'),
        rhDigitalTwin: resolve(__dirname, 'src/modules/rh-11-digital-twin/index.html'),
        rhDisaster: resolve(__dirname, 'src/modules/rh-12-disaster-resilience/index.html'),
        rhFutureTech: resolve(__dirname, 'src/modules/rh-13-future-tech/index.html'),
        rhModelingToolkit: resolve(__dirname, 'src/modules/rh-14-modeling-toolkit/index.html'),
        rhTextbook: resolve(__dirname, 'src/modules/rh-textbook/index.html'),
        rhEpiCalculator: resolve(__dirname, 'src/modules/rh-epi-calculator/index.html'),
        rhEpiTextbook: resolve(__dirname, 'src/modules/rh-epi-textbook/index.html'),
      },
    },
  },
});
